### ISSUE TITLE
`MeasUncerts` undefined in `ESPER_LIR.m`

### ISSUE THREAD

**Issue by jpmattern** [BRCScienceProducts/ESPER#1]
I am currently updating a piece of code to use ESPER instead of LIR v2. There is currently an error in the code that gets triggered, whenever the user specifies measurement uncertainties using `'MeasUncerts'` in the input of `ESPER_LIR`:
```
Undefined function or variable 'MeasUncerts'.

Error in ESPER_LIR (line 254)
    if not(max(size(MeasUncerts)==size(PredictorMeasurements))) && not(min(size(MeasUncerts)==size(PredictorMeasurements))) &&
    not(max(size(MeasUncerts))==0)
```

Sidenote: There is also still a reference to `OAAdjustTF` in the help, even though it is no longer a valid input.
```
% *************************************************************************
% Optional inputs:  All remaining inputs must be specified as sequential
% input argument pairs (e.g. "..., 'Equations',[1:16], 'OAAdjustTF', false,
% etc...")
```

**Comment by BRCScienceProducts** [comment]
Thank you for the bug report, Dr. Mattern!

This was an old issue that had crept back into the most recent files.  I believe it should be fixed in the version that I just pushed, but my unit tests are not comprehensive so please do let me know if you continue to come across this error or others.

The Readme text was an oversight and I've changed the deprecated 'OAAdjustTF' to 'VerboseTF.'

**Comment by jpmattern** [comment]
Excellent, thank you! I can confirm that the error is gone now.
